server:
  port: 8080
titles:
  location: classpath:titles.json
spring:
  jackson:
    default-property-inclusion: non_null
  data:
    mongodb:
      database: titleManager
---
spring:
  profiles: compose
  data:
    mongodb:
      host: mongodb
